import type {
  RuntimeActionDefinitionV1,
} from "./action-catalog";

export const CALENDAR_ACTION_CATALOG: Record<string, RuntimeActionDefinitionV1> = {
  create_event: {
    type: "create_event",
    approvalMode: "required",
    sideEffectKind: "write",
    input: {
      minimum: ["title", "start", "end"],
      optional: ["timezone", "description", "location", "attendees"],
      params: {
        title: {
          key: "title",
          required: true,
          allowedKinds: ["primitive"],
          summary: "Titulo del evento.",
          resourceFamily: "text",
          criticality: "critical",
        },
        start: {
          key: "start",
          required: true,
          allowedKinds: ["time"],
          summary: "Inicio del evento.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        end: {
          key: "end",
          required: true,
          allowedKinds: ["time"],
          summary: "Fin del evento.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        timezone: {
          key: "timezone",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Timezone explicita del evento.",
          resourceFamily: "timezone",
          criticality: "non_critical",
        },
        description: {
          key: "description",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Descripcion textual del evento.",
          resourceFamily: "body",
          criticality: "non_critical",
        },
        location: {
          key: "location",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Ubicacion del evento.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        attendees: {
          key: "attendees",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Invitados con email explicito.",
          resourceFamily: "recipient",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Preview deterministico y encolado de approval/workflow para crear evento.",
    },
  },
  reschedule_event: {
    type: "reschedule_event",
    approvalMode: "required",
    sideEffectKind: "write",
    input: {
      minimum: ["eventRef", "start", "end"],
      optional: ["timezone", "title", "description", "location", "attendees"],
      params: {
        eventRef: {
          key: "eventRef",
          required: true,
          allowedKinds: ["reference"],
          summary: "Evento existente a reprogramar.",
          resourceFamily: "event",
          criticality: "critical",
        },
        start: {
          key: "start",
          required: true,
          allowedKinds: ["time"],
          summary: "Nuevo inicio del evento.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        end: {
          key: "end",
          required: true,
          allowedKinds: ["time"],
          summary: "Nuevo fin del evento.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        timezone: {
          key: "timezone",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Timezone del evento.",
          resourceFamily: "timezone",
          criticality: "non_critical",
        },
        title: {
          key: "title",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Titulo opcional actualizado.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        description: {
          key: "description",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Descripcion opcional actualizada.",
          resourceFamily: "body",
          criticality: "non_critical",
        },
        location: {
          key: "location",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Ubicacion opcional actualizada.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        attendees: {
          key: "attendees",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Invitados actualizados.",
          resourceFamily: "recipient",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Preview y encolado de approval/workflow para reprogramar evento.",
    },
  },
  cancel_event: {
    type: "cancel_event",
    approvalMode: "required",
    sideEffectKind: "destructive",
    input: {
      minimum: ["eventRef"],
      optional: ["reason"],
      params: {
        eventRef: {
          key: "eventRef",
          required: true,
          allowedKinds: ["reference"],
          summary: "Evento existente a cancelar.",
          resourceFamily: "event",
          criticality: "critical",
        },
        reason: {
          key: "reason",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Motivo opcional de cancelacion.",
          resourceFamily: "body",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Preview y encolado de approval/workflow para cancelar evento.",
    },
  },
  list_events: {
    type: "list_events",
    approvalMode: "auto",
    sideEffectKind: "read",
    input: {
      minimum: ["windowStart", "windowEnd"],
      optional: ["timezone", "maxResults"],
      params: {
        windowStart: {
          key: "windowStart",
          required: true,
          allowedKinds: ["time"],
          summary: "Inicio de la ventana a consultar.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        windowEnd: {
          key: "windowEnd",
          required: true,
          allowedKinds: ["time"],
          summary: "Fin de la ventana a consultar.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        timezone: {
          key: "timezone",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Timezone de consulta.",
          resourceFamily: "timezone",
          criticality: "non_critical",
        },
        maxResults: {
          key: "maxResults",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Cantidad maxima de eventos.",
          resourceFamily: "limit",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Lista compacta de eventos dentro de una ventana.",
    },
  },
  check_availability: {
    type: "check_availability",
    approvalMode: "auto",
    sideEffectKind: "read",
    input: {
      minimum: ["windowStart", "windowEnd"],
      optional: ["timezone"],
      params: {
        windowStart: {
          key: "windowStart",
          required: true,
          allowedKinds: ["time"],
          summary: "Inicio de la ventana de disponibilidad.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        windowEnd: {
          key: "windowEnd",
          required: true,
          allowedKinds: ["time"],
          summary: "Fin de la ventana de disponibilidad.",
          resourceFamily: "datetime",
          criticality: "critical",
        },
        timezone: {
          key: "timezone",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Timezone de consulta.",
          resourceFamily: "timezone",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Disponibilidad del calendario en la ventana consultada.",
    },
  },
};
