import type {
  RuntimeActionDefinitionV1,
} from "./action-catalog";

export const CRM_ACTION_CATALOG: Record<string, RuntimeActionDefinitionV1> = {
  search_records: {
    type: "search_records",
    approvalMode: "auto",
    sideEffectKind: "read",
    input: {
      minimum: ["objectType", "query"],
      optional: ["maxResults"],
      params: {
        objectType: {
          key: "objectType",
          required: true,
          allowedKinds: ["primitive", "entity"],
          summary: "Tipo de objeto CRM a buscar.",
          resourceFamily: "record_type",
          criticality: "critical",
        },
        query: {
          key: "query",
          required: true,
          allowedKinds: ["primitive"],
          summary: "Consulta textual o filtro compacto.",
          resourceFamily: "query",
          criticality: "critical",
        },
        maxResults: {
          key: "maxResults",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Cantidad maxima de registros.",
          resourceFamily: "limit",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Busqueda compacta de registros CRM.",
    },
  },
  create_lead: {
    type: "create_lead",
    approvalMode: "required",
    sideEffectKind: "write",
    input: {
      minimum: ["lastName", "company"],
      optional: ["firstName", "email", "phone", "description"],
      params: {
        firstName: {
          key: "firstName",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Nombre del lead.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        lastName: {
          key: "lastName",
          required: true,
          allowedKinds: ["primitive"],
          summary: "Apellido del lead.",
          resourceFamily: "text",
          criticality: "critical",
        },
        company: {
          key: "company",
          required: true,
          allowedKinds: ["primitive"],
          summary: "Empresa del lead.",
          resourceFamily: "text",
          criticality: "critical",
        },
        email: {
          key: "email",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Email del lead.",
          resourceFamily: "recipient",
          criticality: "non_critical",
        },
        phone: {
          key: "phone",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Telefono del lead.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        description: {
          key: "description",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Descripcion del lead.",
          resourceFamily: "body",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Preview y encolado para crear lead en Salesforce.",
    },
  },
  update_lead: {
    type: "update_lead",
    approvalMode: "required",
    sideEffectKind: "write",
    input: {
      minimum: ["recordRef"],
      optional: ["status", "rating", "description"],
      params: {
        recordRef: {
          key: "recordRef",
          required: true,
          allowedKinds: ["reference", "entity"],
          summary: "Lead existente a actualizar.",
          resourceFamily: "record",
          criticality: "critical",
        },
        status: {
          key: "status",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Nuevo status del lead.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        rating: {
          key: "rating",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Nuevo rating del lead.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        description: {
          key: "description",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Descripcion actualizada.",
          resourceFamily: "body",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Preview y encolado para actualizar lead en Salesforce.",
    },
  },
  create_task: {
    type: "create_task",
    approvalMode: "required",
    sideEffectKind: "write",
    input: {
      minimum: ["subject"],
      optional: ["description", "whoRef", "whatRef", "status", "priority", "dueDate"],
      params: {
        subject: {
          key: "subject",
          required: true,
          allowedKinds: ["primitive"],
          summary: "Asunto de la task.",
          resourceFamily: "text",
          criticality: "critical",
        },
        description: {
          key: "description",
          required: false,
          allowedKinds: ["primitive", "computed"],
          summary: "Descripcion de la task.",
          resourceFamily: "body",
          criticality: "non_critical",
        },
        whoRef: {
          key: "whoRef",
          required: false,
          allowedKinds: ["reference", "entity"],
          summary: "Contacto/persona relacionada.",
          resourceFamily: "record",
          criticality: "non_critical",
        },
        whatRef: {
          key: "whatRef",
          required: false,
          allowedKinds: ["reference", "entity"],
          summary: "Objeto relacionado.",
          resourceFamily: "record",
          criticality: "non_critical",
        },
        status: {
          key: "status",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Estado de la task.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        priority: {
          key: "priority",
          required: false,
          allowedKinds: ["primitive"],
          summary: "Prioridad de la task.",
          resourceFamily: "text",
          criticality: "non_critical",
        },
        dueDate: {
          key: "dueDate",
          required: false,
          allowedKinds: ["time"],
          summary: "Fecha de vencimiento.",
          resourceFamily: "date",
          criticality: "non_critical",
        },
      },
    },
    output: {
      summary: "Preview y encolado para crear task en Salesforce.",
    },
  },
};
